export {default as Home} from './oop/Home'
export {default as Chatbot} from './oop/Chatbot'
export {default as Clock} from './oop/Clock'
export {default as Counter} from './oop/Counter'
export {default as Kitty} from './oop/kitty'